name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: debian 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Deploy to cPanel
        uses: peaceiris/actions-cpanel@v2
        with:
          host: 168.119.150.187
          username: skitcomp
          password: 1107luanda1995angola
          path: /public_html
